fieldLayouts:
  e16d16a5-88f2-4cdc-b48d-8aaa3779f2e3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 989e72fc-eb73-4169-99c0-0d571836a06c # Hero Welcome
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec91fffb-3940-43d9-973a-863208173780
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 57d15b3c-e3f6-4dee-ba28-0d135f765a7d # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0dc09bea-8689-4b2f-b132-ead0411131aa
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: efb54d7f-8725-483a-bc7d-e042dfddde35 # Hero CTA
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b531f23-ba9a-48c0-bbc9-a1947bc1c382
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: e6d9418c-f7c7-4146-9eca-151b217df179 # Facebook
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9c8471d-2b14-4291-be90-68cad88369d3
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 35725c51-83e9-4d40-9fac-7c225eb836fd # Instagram
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c198843-003a-49f3-b150-473fd6e1f14f
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: af1df1e6-1223-4efe-9284-72dea06f4b87 # LinkedIN
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a41fc6c1-8efb-4c16-852b-4e90425338d8
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 1b4f3dc4-61ba-4537-a5c5-e0f2d8292b75 # Twitter
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5eb3c047-da48-4099-ba77-73c2d30dfa6b
            userCondition: null
            warning: null
            width: 25
        name: 'Hero Section'
        uid: 8b64e8a9-f115-458a-a1d2-63f742814516
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 40e78b84-9f72-461d-9e96-e7f20dcc527b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 92180d18-f1e2-408c-871e-09b0d1bf0092 # Car Logos
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66607f87-79ba-4322-9940-1a517061aa6f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b15d74d5-fe27-4718-b178-452e33182108
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3ab02981-25ad-470e-b7b0-57d3c05d2997 # Services Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d23cb1f-28b2-4c7a-9fd3-c31e6ad764b2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: caa6ba46-f73d-466f-98cf-5bc710b255cc # Section Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa828d25-9a56-434f-9115-38f80506726f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dbf35501-f8ca-42a9-89d6-3273f4e6be54 # Services Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36f165ff-40b4-4207-b3e4-711de75e2cc4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 310b0c71-efdc-4094-9780-69a40f8a4987 # Services CTA Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26c46f2e-c826-45fa-91e4-20b660606f20
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b233643d-7aa7-4e93-a877-506de03c48c2 # Services Entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4c90577-84f7-453d-995e-cacdc4f61d14
            userCondition: null
            warning: null
            width: 100
        name: 'Service Section'
        uid: 3359b9fc-5503-44a8-ad09-59f51fe3d3e3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 93b37745-a740-4416-ac5e-330a9551037d # Install Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7769c00-1a9d-4b1c-9ec4-8dc37b95e130
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 435e168f-db13-4793-81b9-924d7d4fe847 # Install Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a63445d5-8fc1-4717-98f7-7415d3a490fb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f3f9fdba-5213-49ec-8e6c-6147b846d3ea # Install Bullets
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00910d67-99cc-4658-ba9e-04d753356390
            userCondition: null
            warning: null
            width: 100
        name: Installation
        uid: 4de21f33-f5e3-4383-9bfa-a1bbd79495b5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6eba2d02-08de-4fe3-b927-933981336cf2 # FAQ Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89b19a8d-6d1d-46db-8ec1-036704882346
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0afa1926-f7cb-4bfd-8ef5-106fc8c40267 # FAQ Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82d16cc4-529a-4019-90af-adb7bc573a4d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 896d9c7f-9c64-412b-8a55-84c443c8c15c # FAQ Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6f2688a-40b2-420e-9842-c3af59358b2d
            userCondition: null
            warning: null
            width: 100
        name: FAQ
        uid: 3a640dc1-c3a8-4d92-ad3f-1b02693f0806
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 422baf31-1e59-435c-bf97-dbb98d3d7385 # Recent Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c01c4c45-9498-428c-b7fb-953eafb4cb3e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 47aca4be-13f6-42a5-b94d-39aed75a64a3 # Recent Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e80b4ac-228d-4684-91bb-073043e09d24
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 85934e8f-1a39-42c4-992c-cce465fd76fd # Recent CTA Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6144effd-93b0-4c40-8767-95bd6a0042f2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dad15833-2cda-4530-857d-d1abd0add5d7 # Recent CTA Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c60b3c1c-5369-44b5-a675-b7cad726cbb7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 11b1499d-be7a-42a4-8900-b62fd7c51d72 # Blog Section Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72d64fca-dd1f-46a4-983e-cbc7aa9c7ae7
            userCondition: null
            warning: null
            width: 100
        name: 'Blog Section'
        uid: 7f1abbf2-f182-47e1-b0bd-b49adaa056c9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2c13bf6b-ae6d-4d53-b34a-89d4b65f5d2d # Testimonials Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3e80148-8ce9-4ab0-b363-7f7aab6af808
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f5ef656c-3bf4-422e-8ccd-df4920da3b77 # Testimonials Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81113ef9-cd64-4f4c-8602-635ec1214ce1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1d18e928-59e9-4a8d-8036-ad9b4dd9b6f3 # Testimonials
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b375af4-ea12-42b3-8e59-4919b103814e
            userCondition: null
            warning: null
            width: 100
        name: Testimonials
        uid: 39b7e8af-e5fb-47b7-aa16-a8a27893617f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b975fc17-df67-4df0-842a-6a5e998bdcd6 # App Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbe49045-25d5-4390-8e4c-ccaabf7302fd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8030a0b0-5fd4-4c94-998d-f26d919f92f5 # App Main Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ce732c3-5f72-4afc-8a00-8027d01f0af3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9ad2d0e7-8a45-4415-8c2d-37f4f5f0d53b # App Body Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43a7c66f-31da-4038-8377-51f7f460304d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bcd9ec03-b9a0-442d-9c2b-ca6162a919e8 # Android App Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28a7ef67-3d4c-4d88-84d0-dfa98aa60c7c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 662a6012-d72b-4297-b33e-e4d8a9ff4d7f # App iOS LInk
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9bee990d-754e-4312-97a2-e4ccbf5aca88
            userCondition: null
            warning: null
            width: 100
        name: App
        uid: 036062ae-2ad8-453c-9945-c322b4b9226f
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: 10b131d9-f5f8-42c1-96f2-672d45fbb95c # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
