columnSuffix: cqwcofdb
contentColumnType: text
fieldGroup: 395c13aa-7eba-4619-9ce8-a82bbaff1cc4 # Common
handle: mainContent
instructions: null
name: 'Main Content'
searchable: false
settings:
  availableTransforms:
    - b9f3fb12-9462-4618-8d2a-202a97e8e2e1 # Transform1
  availableVolumes:
    - 09e5bcec-ebd8-4ddc-86c8-9e86be6489c9 # Uploads
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: null
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showHtmlButtonForNonAdmins: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
