defaultPlacement: end
enableVersioning: true
handle: blog
name: Blog
propagationMethod: all
siteSettings:
  0e727dac-2a07-4e2a-99a8-683fa8a5e93a: # EGO EV
    enabledByDefault: true
    hasUrls: true
    template: blog/index.twig
    uriFormat: blog
type: single
